### ISSUE TITLE
introspection of union type?

### ISSUE THREAD

**Issue by dovahcrow** [joshprice/graphql-elixir#107]
When I wrote down this in my graphql schema, introspection in graphiql failed with `Introspection must provide object type for possibleTypes.`
![image](https://cloud.githubusercontent.com/assets/998606/19217868/a9db4f50-8e19-11e6-8579-306a3cabb633.png)
Seems like the implementation [`defimpl AbstractType`](https://github.com/graphql-elixir/graphql/blob/master/lib/graphql/type/union.ex#L16) not works at all

**Comment by aweiker** [comment]
You can't use a scalar type in a union. see: http://facebook.github.io/graphql/#sec-Union-type-validation

**Comment by dovahcrow** [comment]
I see, thanks
