### ISSUE TITLE
Parser results: Maps vs Keyword Lists?

### ISSUE THREAD

**Issue by bruce** [joshprice/graphql-elixir#17]
Looking at, eg, https://github.com/joshprice/graphql-elixir/blob/master/test/graphql_parser_schema_kitchen_sink_test.exs

Might it make more sense for the parser to produce maps vs keyword lists for better traversal by pattern matching?

**Comment by 1player** [comment]
+1

Keyword lists have better memory usage compared to maps, but they are a pain to pattern match with as the order of fields in the pattern is important.

**Comment by bruce** [comment]
This is the sort of thing that will take a lot of tedious test edits; I'll put together a PR for review.
