### ISSUE TITLE
Need to figure out how to represent the parsed GraphQL structure so it can be useful

### ISSUE THREAD

**Issue by joshprice** [joshprice/graphql-elixir#2]
I've been focussing on getting lexing and parsing to work correctly, and have a simple but likely not very useful structure just so I can understand the output and check it is working as expected with tests.

So this needs to change but just not sure how yet.

Want to tackle this before writing too many more specs because the specs are getting harder to read, and there will be more to change if I leave this until later.

**Comment by freshtonic** [comment]
I agree.  I think this means that now it the time to understand the GraphQL spec more completely.

https://facebook.github.io/graphql/

And then figure out how to proceed from there.

**Comment by joshprice** [comment]
Happy to keep trucking with it as is until we can parse the entire spec, but it's getting a bit awkward to even test with.

**Comment by joshprice** [comment]
The Execution section of the spec may be particularly useful https://facebook.github.io/graphql/#sec-Execution

**Comment by joshprice** [comment]
Have used the reference AST, happy with this for now.
