### ISSUE TITLE
Complex types under status

### ISSUE THREAD

**Issue by triptec** [joshprice/graphql-elixir#28]
I was looking at the status and it's my understanding that lists aren't implemented but there is a test that looks like it is testing a list

```
    test "lists of things" do
```

I'm confused

**Comment by joshprice** [comment]
Apologies, I haven't updated the current status, lists are implemented as `%GraphQL.List{of_type: <list_type>}`. Try the schema syntax in that test https://github.com/joshprice/graphql-elixir/blob/master/test/graphql/execution/executor_test.exs#L144-L150
