### ISSUE TITLE
Elixir channel in GraphQL Slack

### ISSUE THREAD

**Issue by anthonator** [joshprice/graphql-elixir#30]
I just wanted to note that I created an Elixir channel in the GraphQL Slack team.

**Comment by joshprice** [comment]
Thanks, I did consider creating this initially but then realised that it was probably better to have an `erlang` in the same way that there is a `#jvm` chanel. Still useful to have if people are searching for `elixir` vs `erlang`, mind if we add a pointer to `#erlang`?
