### ISSUE TITLE
Validation

### ISSUE THREAD

**Issue by joshprice** [joshprice/graphql-elixir#35]
Implement query validation

**Comment by plasticine** [comment]
:hand:

**Comment by freshtonic** [comment]
This is currently being worked on.

**Comment by plasticine** [comment]
@freshtonic would be keen to see how you tackle it. Have you thought about how to tackle validations that need to traverse the whole schema? I started to have a look at that in #36, but wasn't super happy with where I got to with it.

**Comment by freshtonic** [comment]
@joshprice Dealing with the whole schema (for checking field usages in the AST really do exist in their types) is what led me to revisit the visitors ROFL.

In functional programming land, we need something that works like a reducer (for validations, take a validator as input to an "AST reducer", which returns `:ok` or `{errors: [...]}`).  I'm investigating prior work in the area.

**Comment by plasticine** [comment]
@freshtonic check out how absinthe handles being able to reduce. That's mainly what I was unhappy with in my implementation.

**Comment by freshtonic** [comment]
@plasticine I had a look, but it seems incomplete and there are no validator implementations yet. Maybe I'm looking in the wrong spot...?

**Comment by plasticine** [comment]
@freshtonic typing on a phone from rubyconf is not ideal. Haha, sorry. Yeah, it is incomplete; the nice bit is that nodes define their children, meaning that they can traverse without needing that horrible module var at the top of my visitor.

**Comment by freshtonic** [comment]
@plasticine right, but then we'd need to create a bunch of structs, one for each node type and have them implement a protocol. I'm ok with the `@nodes` variable, FWIW.

**Comment by plasticine** [comment]
@freshtonic yep, that's kinda where I ended up, also none of the type stuff really existed when most of this was written. Does allow for more reduce style traversal though.

**Comment by joshprice** [comment]
Validations are now wired up #79 so closing this. Let's open separate issues for remaining validations.
