### ISSUE TITLE
Introspection doesn't show mutation

### ISSUE THREAD

**Issue by drewblas** [joshprice/graphql-elixir#52]
I believe you're already aware, but introspection (and therefore completion/docs on GraphiQL) don't show mutation/subscription, even when those are available.

I tracked the offending line to https://github.com/joshprice/graphql-elixir/blob/3171ad8af07cbe7e11c962bf9bd074516049d2da/lib/graphql/type/introspection.ex#L34  

However, I don't know how to fix this to get it to report the mutation (beyond uncommenting, which didn't work).  If I could get a little guidance, I'd love to help!

**Comment by joshprice** [comment]
Thanks for the bug report! I'll take a look later today. If you want to have a go at fixing it feel free, it should look much like the query block.

**Comment by joshprice** [comment]
Going to look into this now if you're around, ping me in the slack channel

**Comment by drewblas** [comment]
Hi Josh,

Any luck by chance?  I'm still working to try to fix this myself, but I'm afraid I'm not getting far.

**Comment by joshprice** [comment]
Not as yet, there is a bit more to this than anticipated so hoping get it fixed as soon as I can. Thanks for your patience!

**Comment by joshprice** [comment]
Closed by #55

**Comment by joshprice** [comment]
Thanks for the bug report, sorry it took so long! We'll make a release today so you can check it out.

**Comment by drewblas** [comment]
Thanks Josh, greatly appreciated!

**Comment by joshprice** [comment]
No worries, released now if you want to check it out
