### ISSUE TITLE
Implement Directives

### ISSUE THREAD

**Issue by markolson** [joshprice/graphql-elixir#58]
Per [Section 3.2](https://facebook.github.io/graphql/#sec-Type-System.Directives), we need to support Directives, and provide the `@skip` and `@include` ones by default

**Comment by seanabrahams** [comment]
@joshprice @markolson Has anyone done any work on directives yet? Just want to check before I take a look at implementing them. Thanks!

**Comment by joshprice** [comment]
Not that I'm aware of. Go for it!
