### ISSUE TITLE
How can I return an error to the client with a mutation?

### ISSUE THREAD

**Issue by dre1080** [joshprice/graphql-elixir#64]
Whenever I execute a mutation I can never seem to produces errors as stated here: https://facebook.github.io/graphql/#sec-Errors

How do I produce errors?

**Comment by aweiker** [comment]
Did a bunch of tracking down and [`GraphQL.Execution.Executor.report_error/2`](https://github.com/joshprice/graphql-elixir/blob/master/lib/graphql/execution/executor.ex#L29) mutates the context parameter and returns a new context, but we don't actually use the new value that has the error in it. 

When using [`put_in/3`](http://elixir-lang.org/docs/stable/elixir/Kernel.html#put_in/3) it returns a new value with the change.

**Comment by dre1080** [comment]
@aweiker I saw the same thing.

I finally came up with a solution.
At the moment, this is what I'm doing for errors:

``` elixir
defmodule GraphQL.InvalidChangesetError do
  @moduledoc """
  Exception raised when Ecto Changeset is invalid.
  """

  defexception plug_status: 422, message: "invalid changeset", changeset: nil, errors: %{}

  @doc false
  def exception(opts) do
    changeset = Keyword.fetch!(opts, :changeset)
    errors = changeset.errors

    %GraphQL.InvalidChangesetError{
      message: "invalid changeset for (#{changeset.data.__struct__}): #{inspect errors}",
      changeset: changeset,
      errors: errors
    }
  end
end
```

These are errors that have to do with uniqueness & querying the db.

Then added the following to my `ErrorView`:

``` elixir
def render("422.json", assigns) do
    {_, _, _, stack} = hd(assigns[:stack])
    {field, message} = hd(assigns[:reason].errors)
    %{errors: [%{message: "#{field} #{message}",
                 file: to_string(stack[:file]),
                 line: stack[:line]}]}
end
```

Now whenever I need to produce an error to the client I `raise/2` a `GraphQL.InvalidChangesetError` like so: 

``` elixir
raise GraphQL.InvalidChangesetError, changeset: changeset
```

This now returns an appropriate error object that Relay can understand.

**Comment by joshprice** [comment]
Related to #56

**Comment by bringking** [comment]
Any status on this? From reading the spec, if we can't bubble errors during query execution, then the library isn't spec compliant.
