### ISSUE TITLE
Default values for arguments are not used

### ISSUE THREAD

**Issue by aweiker** [joshprice/graphql-elixir#67]
I setup a simple query that took set a default value, then did not set the input variable and it should have used the default value.

Query: 

``` javascript
query name($name: String = "Joe")
{
  greeting(name: $name)
}
```

If I set `$name` then the query executes, but if I don't the value is empty.

I tested this against the node version and it performed as expected.

**Comment by joshprice** [comment]
This was working in GraphQL fine, but seems to be broken in the playground. Pushing an update which should fix this now.

**Comment by joshprice** [comment]
Working now: http://playground.graphql-elixir.org/graphql/hello?query=query%20g(%24name%3AString%3D%22Joe%22)%7Bgreeting(name%3A%24name)%7D
