### ISSUE TITLE
Arguments should be treated as not present when there is no Input Variable

### ISSUE THREAD

**Issue by aweiker** [joshprice/graphql-elixir#68]
## Reproduced Behavior in GraphQL-JS

When using arguments in a query, if the variable is not set the query should treat that argument like it does not exist.
### Example Query

``` Javascript
query hello($name: String, $episode: Episode) {
  hello(name: $name, episode: $episode)
}
```
### Query variables

``` Javascript
{
  "episode" : "JEDI"
}
```

In this case the value of `name` will be `undefined` when the resolve function is executed.
## Experienced behavior in GraphQL-Elixir

When executing this same type of query in GraphQL-Elixir, it will use the default value for a string which is  `""`.

When not specifying an Enum, it will try to parse `nil` and will throw an exception in the _defimpl_ of `GraphQL.Types.parse_value` for `GraphQL.Type.Enum`.

**Comment by joshprice** [comment]
Fixed http://playground.graphql-elixir.org/graphql/starwars?query=query%20hello(%24name%3A%20String%2C%20%24episode%3A%20Episode)%20%7B%0A%20%20hello(name%3A%20%24name%2C%20episode%3A%20%24episode)%0A%7D%0A&variables=%7B%0A%20%20%22episode%22%20%3A%20%22JEDI%22%0A%7D
