### ISSUE TITLE
Question: it's not supposed to be used with pure Erlang, and never gonna be?

### ISSUE THREAD

**Issue by vladimir-vg** [joshprice/graphql-elixir#77]
subj.

If I want to use GraphQL with Erlang, not with Elixir, I need to write alternative implementation, that's right?

**Comment by joshprice** [comment]
Unlike Absinthe we're not using macros (yet) so I'm not aware of any reason that this library couldn't be used directly from pure Erlang. That said I haven't tried it, so if you try it, it'd be great to know what you find!

**Comment by joshprice** [comment]
Closing this question, please report anything you find here: https://github.com/graphql-elixir/graphql/issues/78

Ideally it'd be possible to call GraphQL Elixir from Erlang.
