### ISSUE TITLE
TestHelper is mostly unnecessary

### ISSUE THREAD

**Issue by freshtonic** [joshprice/graphql-elixir#85]
Instead of many permutations of `assert_execute_*`, let's just have our tests invoke `GraphQL.execute`, get the response (which may or may not include errors) and check assert on the response directly.

`GraphQL.execute` is now easier to use because of the use of keyword lists. It means we don't need all of the assert permutations to make it usable anymore.

**Comment by aweiker** [comment]
I like this and it also makes the tests easier to maintain and read as you don't need to know the correct tuple form.

**Comment by freshtonic** [comment]
Closed by https://github.com/graphql-elixir/graphql/pull/86
