### ISSUE TITLE
InputObjectType should be supported

### ISSUE THREAD

**Issue by proProbe** [joshprice/graphql-elixir#97]
http://graphql.org/docs/api-reference-type-system/#graphqlinputobjecttype

**Comment by joshprice** [comment]
Does this not do what you need? https://github.com/graphql-elixir/graphql/blob/master/test/graphql/execution/variables_test.exs#L137-L173

If this isn't what you're after can you please provide some more context so it can be reproduced?

**Comment by joshprice** [comment]
Closing as this has been resolved
